name: aria2cf
description: "aria2cf."
version: 0.0.1
homepage: "localhost"

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  json_rpc_2: ^3.0.2
  process_run: ^1.2.0+1
  web_socket_channel: ^3.0.1
  rxdart: ^0.28.0
  worker_manager: ^7.2.1
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^5.0.0
  test: ^1.24.8


